// Generated by scripts/fetch-web-fonts.ts — do not edit by hand.
export const fontPreloads = [
	'/fonts/google/inter-latin-c9407645.woff2',
	'/fonts/google/eb-garamond-latin-68fd4b24.woff2',
	'/fonts/google/noto-sans-coptic-coptic-b5b1c927.woff2',
	'/fonts/google/noto-naskh-arabic-arabic-bb07eddb.woff2',
]
