packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@biomejs/biome': true
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-ses@3.1051.0'
