/**
 * English language data exports
 */

// Synaxarium - pre-built search index for O(1) lookups
// Generated by: pnpm --filter @coptic/data build:index
export { default as synaxariumIndex } from './synaxarium/indexed.json'
export { default as synaxariumCanonical } from './synaxarium/canonical.json'

export const LANGUAGE = 'en' as const

export const AVAILABLE_SOURCES = ['canonical', 'st-takla', 'suscopts'] as const
