/**
 * Web font vendoring
 *
 * Mirrors the Google Fonts CSS for the web app's fonts into apps/web/app/fonts so
 * `next build` never touches the network. Every subset block Google serves is kept
 * (same unicode-range splits as next/font/google), so rendering is unchanged.
 * All fonts are SIL OFL 1.1; each font's license travels with it in fonts/licenses.
 *
 * Run with: pnpm fonts:fetch
 */

import { createHash } from 'node:crypto'
import * as fs from 'node:fs'
import * as path from 'node:path'

const FONTS_DIR = path.join(import.meta.dirname, '../apps/web/app/fonts')
const FILES_DIR = path.join(FONTS_DIR, 'files')
const LICENSES_DIR = path.join(FONTS_DIR, 'licenses')
const CSS_PATH = path.join(FONTS_DIR, 'fonts.css')
const LICENSE_BASE_URL = 'https://raw.githubusercontent.com/google/fonts/main/ofl'

// Google only serves woff2 to browsers it recognises
const USER_AGENT =
	'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

interface WebFont {
	/** CSS custom property the app reads the family from */
	variable: string
	/** css2 `family=` value */
	query: string
	/** Directory under google/fonts/ofl holding the font's OFL.txt */
	licenseDir: string
}

const FONTS: WebFont[] = [
	{ variable: '--font-inter', query: 'Inter:wght@100..900', licenseDir: 'inter' },
	{ variable: '--font-serif', query: 'EB Garamond:wght@400..800', licenseDir: 'ebgaramond' },
	{ variable: '--font-coptic', query: 'Noto Sans Coptic', licenseDir: 'notosanscoptic' },
	{
		variable: '--font-arabic',
		query: 'Noto Naskh Arabic:wght@400;500;600',
		licenseDir: 'notonaskharabic',
	},
]

const BLOCK = /\/\* ([\w-]+) \*\/\s*@font-face \{([^}]*)\}/g

const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-')

const familyOf = (query: string) => query.split(':')[0]

async function fetchText(url: string): Promise<string> {
	const res = await fetch(url, { headers: { 'User-Agent': USER_AGENT } })
	if (!res.ok) throw new Error(`${res.status} fetching ${url}`)
	return res.text()
}

async function fetchBytes(url: string): Promise<Buffer> {
	const res = await fetch(url)
	if (!res.ok) throw new Error(`${res.status} fetching ${url}`)
	return Buffer.from(await res.arrayBuffer())
}

async function vendorFont(font: WebFont): Promise<string> {
	const family = familyOf(font.query)
	const cssUrl = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(font.query)}&display=swap`
	const css = await fetchText(cssUrl)

	const blocks: string[] = []
	for (const [, subset, body] of css.matchAll(BLOCK)) {
		const src = body.match(/url\(([^)]+)\)/)?.[1]
		if (!src) throw new Error(`Unexpected @font-face for ${family} (${subset})`)

		const bytes = await fetchBytes(src)
		const hash = createHash('sha256').update(bytes).digest('hex').slice(0, 8)
		// Content-addressed, so weights Google serves from one variable file share it
		const fileName = `${slugify(family)}-${subset}-${hash}.woff2`
		fs.writeFileSync(path.join(FILES_DIR, fileName), bytes)

		const localBody = body.replace(src, `"./files/${fileName}"`)
		blocks.push(`/* ${subset} */\n@font-face {${localBody}}`)
	}

	if (blocks.length === 0) throw new Error(`No @font-face blocks returned for ${family}`)

	const license = await fetchText(`${LICENSE_BASE_URL}/${font.licenseDir}/OFL.txt`)
	fs.writeFileSync(path.join(LICENSES_DIR, `${slugify(family)}-OFL.txt`), license)
	console.log(`${family}: ${blocks.length} files`)
	return blocks.join('\n')
}

async function main() {
	for (const dir of [FILES_DIR, LICENSES_DIR]) {
		fs.rmSync(dir, { recursive: true, force: true })
		fs.mkdirSync(dir, { recursive: true })
	}

	const faces: string[] = []
	for (const font of FONTS) faces.push(await vendorFont(font))

	const variables = FONTS.map((font) => `\t${font.variable}: "${familyOf(font.query)}";`).join('\n')
	const header = [
		'/* Generated by scripts/fetch-web-fonts.ts — do not edit by hand.',
		'   Source: Google Fonts. Licensed under the SIL Open Font License 1.1; see ./licenses. */',
	].join('\n')

	fs.writeFileSync(CSS_PATH, `${header}\n\n${faces.join('\n')}\n\n:root {\n${variables}\n}\n`)
}

main().catch((error) => {
	console.error(error)
	process.exit(1)
})
