/**
 * Cross-language integrity checks for the Agpeya data.
 *
 * The reader renders English and Arabic side by side in aligned rows, so the
 * two files should be parallel texts: every prose block split into the same
 * number of lines, and every psalm divided into the same verses. Arabic is the
 * canonical text (embedded St-Takla liturgical psalter); English currently
 * resolves psalms from the Bible (Masoretic-style versification) and packs
 * prose into fewer lines, so most sections don't match yet.
 *
 * KNOWN_*_GAPS below is that backlog, generated by
 * `npx tsx scripts/agpeya-gap-report.ts`. The lists ratchet:
 *   - a section NOT listed must match exactly (no new drift can sneak in),
 *   - a section listed must STILL mismatch — fixing the data without removing
 *     its entry fails the test, so the lists always equal the remaining work.
 */
import { describe, expect, it } from 'vitest'
// Compare LOADER output, not raw JSON — an hour file names most of its sections
// by id, so only the composed hour is the text actually served.
import {
	getAgpeyaHourIds as arHourIds,
	getAgpeyaHour as getArAgpeyaHour,
	getAgpeyaHourData as getArHour,
} from '../ar/agpeya'
import {
	getAgpeyaHourIds,
	getAgpeyaHour as getEnAgpeyaHour,
	getAgpeyaHourData as getEnHour,
} from '../en/agpeya'
import enBible from '../en/bible/books.json'

const KNOWN_PROSE_GAPS = new Set([
	'prime.litanies',
	'terce.litanies',
	'terce.closing',
	'sext.litanies',
	'none.litanies',
	'vespers.litanies',
	'vespers.closing',
	'compline.litanies',
	'compline.closing',
	'midnight.opening',
	'midnight.closing',
	'midnight.midnight-1.litanies',
	'midnight.midnight-1.closing',
	'midnight.midnight-2.litanies',
	'midnight.midnight-2.closing',
	'midnight.midnight-3.litanies',
	'midnight.midnight-3.closing',
])

const KNOWN_PSALM_GAPS = new Set<string>([])

// ── data walking ─────────────────────────────────────────────────────────────

interface Block {
	content?: string[]
}
interface Psalm {
	verses?: unknown[]
}
interface Unit {
	[key: string]: unknown
	psalmRefs?: { psalmNumber: number }[]
	psalms?: Psalm[]
	introductoryPsalm?: Psalm & { psalmNumber?: number }
	watches?: (Unit & { id: string })[]
}

const isBlock = (v: unknown): v is Block =>
	typeof v === 'object' && v !== null && Array.isArray((v as Block).content)

const units: { path: string; en: Unit; ar: Unit }[] = getAgpeyaHourIds().flatMap((hourId) => {
	const e = (getEnHour(hourId) ?? {}) as Unit
	const a = (getArHour(hourId) ?? {}) as Unit
	return [
		{ path: hourId, en: e, ar: a },
		...(e.watches ?? []).map((watch, i) => ({
			path: `${hourId}.${watch.id}`,
			en: watch as Unit,
			ar: (a.watches?.[i] ?? {}) as Unit,
		})),
	]
})

// English psalms resolve from the Bible via LXX→Masoretic mapping. Mirrors
// lxxPsalmSegments in apps/api/src/services/psalm-resolver.ts (runtime source
// of truth) — keep the two in sync.
const enPsalmsBook = (
	enBible as { books: { name: string; chapters: { num: number; verses: unknown[] }[] }[] }
).books.find((b) => b.name === 'Psalms')
function lxxSegments(n: number): { chapter: number; start?: number; end?: number }[] {
	if (n <= 8) return [{ chapter: n }]
	if (n === 9) return [{ chapter: 9 }, { chapter: 10 }]
	if (n <= 112) return [{ chapter: n + 1 }]
	if (n === 113) return [{ chapter: 114 }, { chapter: 115 }]
	if (n === 114) return [{ chapter: 116, start: 1, end: 9 }]
	if (n === 115) return [{ chapter: 116, start: 10, end: 19 }]
	if (n <= 145) return [{ chapter: n + 1 }]
	if (n === 146) return [{ chapter: 147, start: 1, end: 11 }]
	if (n === 147) return [{ chapter: 147, start: 12, end: 20 }]
	if (n <= 150) return [{ chapter: n }]
	return []
}
function enVerseCount(lxx: number): number {
	return lxxSegments(lxx).reduce((sum, seg) => {
		const ch = enPsalmsBook?.chapters.find((c) => c.num === seg.chapter)
		if (!ch) return sum
		return (
			sum + (seg.start != null ? (seg.end ?? ch.verses.length) - seg.start + 1 : ch.verses.length)
		)
	}, 0)
}

// Every comparable site → line/verse counts per language.
const proseCounts = new Map<string, { en: number; ar: number }>()
const psalmCounts = new Map<string, { en: number; ar: number }>()
for (const { path, en: e, ar: a } of units) {
	const keys = [...new Set([...Object.keys(e), ...Object.keys(a)])].filter(
		(k) => isBlock(e[k]) || isBlock(a[k]),
	)
	for (const key of keys) {
		proseCounts.set(`${path}.${key}`, {
			en: isBlock(e[key]) ? (e[key] as Block).content!.length : 0,
			ar: isBlock(a[key]) ? (a[key] as Block).content!.length : 0,
		})
	}
	;(e.psalmRefs ?? []).forEach((ref, i) => {
		const arCount = a.psalms?.[i]?.verses?.length ?? 0
		// No Arabic embedding → runtime resolves both languages the same way.
		if (arCount === 0) return
		// English serves its embedded liturgical psalm when present, else the Bible.
		const enCount = e.psalms?.[i]?.verses?.length ?? enVerseCount(ref.psalmNumber)
		psalmCounts.set(`${path}/psalm-${ref.psalmNumber}`, { en: enCount, ar: arCount })
	})
	if (e.introductoryPsalm?.psalmNumber != null && a.introductoryPsalm?.verses?.length) {
		psalmCounts.set(`${path}/intro-psalm`, {
			en: enVerseCount(e.introductoryPsalm.psalmNumber),
			ar: a.introductoryPsalm.verses.length,
		})
	}
}

// ── invariants ───────────────────────────────────────────────────────────────

describe('agpeya rite parity', () => {
	// The strongest invariant the order-based split buys: both languages name the
	// same section ids in the same sequence, so the reader can align them by id
	// instead of by position and a section added to one language but not the
	// other fails here rather than silently misaligning the columns.
	const MISSING_ARABIC = new Set(['midnight-1-closing', 'midnight-2-closing', 'midnight-3-closing'])

	it('prays the same sections in the same order in both languages', () => {
		for (const hourId of getAgpeyaHourIds()) {
			const ids = (hour: ReturnType<typeof getEnAgpeyaHour>): string[] =>
				(hour?.parts ?? []).flatMap((part) =>
					'group' in part ? [part.group, ...part.sections.map((s) => s.id)] : [part.id],
				)
			const en = ids(getEnAgpeyaHour(hourId)).filter((id) => !MISSING_ARABIC.has(id))
			expect(ids(getArAgpeyaHour(hourId)), `${hourId}: order differs`).toEqual(en)
		}
	})

	it('lists only still-missing sections in MISSING_ARABIC', () => {
		const arabic = new Set(
			getAgpeyaHourIds().flatMap((hourId) =>
				(getArAgpeyaHour(hourId)?.parts ?? []).flatMap((part) =>
					'group' in part ? part.sections.map((s) => s.id) : [part.id],
				),
			),
		)
		for (const id of MISSING_ARABIC) {
			expect(arabic.has(id), `${id} now exists in Arabic — remove it from MISSING_ARABIC`).toBe(
				false,
			)
		}
	})
})

describe('agpeya data cross-language parity', () => {
	it('has identical hours and psalm sequences', () => {
		expect(arHourIds()).toEqual(getAgpeyaHourIds())
		for (const { path, en: e, ar: a } of units) {
			const nums = (u: Unit) => (u.psalmRefs ?? []).map((r) => r.psalmNumber)
			expect(nums(a), `${path}: psalmRefs differ`).toEqual(nums(e))
		}
	})

	it('splits prose blocks into the same lines (ratcheted by KNOWN_PROSE_GAPS)', () => {
		for (const [path, { en: e, ar: a }] of proseCounts) {
			if (KNOWN_PROSE_GAPS.has(path)) {
				expect(e, `${path} now matches (${e} lines) — remove it from KNOWN_PROSE_GAPS`).not.toBe(a)
			} else {
				expect(`${path}: en=${e} ar=${a}`).toBe(`${path}: en=${e} ar=${e}`)
			}
		}
	})

	it('divides psalms into the same verses (ratcheted by KNOWN_PSALM_GAPS)', () => {
		for (const [id, { en: e, ar: a }] of psalmCounts) {
			if (KNOWN_PSALM_GAPS.has(id)) {
				expect(e, `${id} now matches (${e} verses) — remove it from KNOWN_PSALM_GAPS`).not.toBe(a)
			} else {
				expect(`${id}: en=${e} ar=${a}`).toBe(`${id}: en=${e} ar=${e}`)
			}
		}
	})

	it('lists only real sections in the gap ratchets (stale entries mean the data moved)', () => {
		for (const path of KNOWN_PROSE_GAPS) {
			expect(proseCounts.has(path), `${path} not found — remove it from KNOWN_PROSE_GAPS`).toBe(
				true,
			)
		}
		for (const id of KNOWN_PSALM_GAPS) {
			expect(psalmCounts.has(id), `${id} not found — remove it from KNOWN_PSALM_GAPS`).toBe(true)
		}
	})
})
